export const ADD = 'add'
export const DELETE = 'delete'
export const ON_MOUSE_OVER = 'onMouseOver'
export const CLICK_TODOS_BY_INDEX = 'clickTodosByIndex'
export const CLICK_ALL_CHECKBOX = 'clickAllCheckbox'
export const CLEAR_TODOS = 'clearTodos'